theme: minima
title: Open Source Journey Documentation
author: Zeal Shah
description: Hello readers, I've started my open source journey and have decided to document the difficulties I faced on the way. If you feel like  adding additional information to the  documentation, feel free to contribute. Happy coding :) 
